### ISSUE TITLE
关于app

### ISSUE THREAD

**Issue by dcafj** [G-Pegasus/YanLuApp#1]
你好，我是准备24考研的小伙伴，希望能给点推荐！
你的app，我在安卓模拟器上注册不上，不知道是啥情况。
兄弟你是几几年考研的学生还是已经上岸了？

**Comment by G-Pegasus** [comment]
我也是24考研的，模拟器注册不上的话你拿真机试一下呢

**Comment by dcafj** [comment]
兄弟，你考哪个大学啊？


------------------ 原始邮件 ------------------
发件人: Kana ***@***.***&gt;
发送时间: 2023年3月13日 12:56
收件人: G-Pegasus/YanLuApp ***@***.***&gt;
抄送: dcafj ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[G-Pegasus/YanLuApp] 关于app (Issue #1)





 
我也是24考研的，模拟器注册不上的话你拿真机试一下呢

**Comment by G-Pegasus** [comment]
看情况吧，目前打算东北大学

**Comment by G-Pegasus** [comment]
stop
